baseURL = "https://blog.h11.io/"
languageCode = "zh-Hans"
title = "H11"
theme = "hugo-xmin"
googleAnalytics = "UA-78944716-1"

[params]
    description = "H11's blog"
    footer = "&copy; H11 | [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 100

[blackfriday]
extensions = ["hardLineBreak"]
