name: deploy

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'note/**'

jobs:
    build-deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: peaceiris/actions-hugo@v2.4.7
              with:
                  hugo-version: '0.68.3'
            - run: hugo --minify
            - uses: peaceiris/actions-gh-pages@v3.5.6
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./public
                  publish_branch: gh-pages
                  force_orphan: true
